name: Create Release

on:
    push:
        tags:
        - 'v*'
        
env:
  tag: ${{ github.ref }}
  
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: ${{ env.tag }}
          body: |
            Please refer to CHANGELOG.md for details.
          draft: false
          prerelease: false
